### ISSUE TITLE
Diagram class

### ISSUE THREAD

**Issue by nrrf** [serconexion/serconexion-diagrams#2]
No se si tomamos base de lo q hicimos en drawio o reeplanteamos uno nuevo hasta lo hecho a hoy, creo q este es delicado, ya que cada uno lo puede ver de manera distinta

**Comment by yuri4n** [comment]
Creo que habra que hacer uno nuevo, porque el de draw.io le eche un ojo y esta medio incompleto se me hace a mi, pero no se que opinen @ImGAMP @AlejaCE

**Comment by nrrf** [comment]
Podríamos reunirnos mañana viernes y lo hacemos entre todos, no? , q opinan @ImGAMP , @yurianxdev , @AlejaCE

**Comment by yuri4n** [comment]
Se acordo construir los diagramas por separado y juntarlos para la presentacion
